models:
  qwen2.5-vl:
    model_name_or_path: Qwen/Qwen2.5-VL-7B-Instruct 
    attn_implementation: flash_attention_2
    device_map: auto

  qwen3-embed:
    model_name_or_path: Qwen/Qwen3-Embedding-0.6B
    attn_implementation: flash_attention_2
    device_map: auto

  qwen3-rerank:
    model_name_or_path: Qwen/Qwen3-Reranker-0.6B
    attn_implementation: flash_attention_2
    device_map: auto

record_path: inference_records.jsonl